### ISSUE TITLE
Packages are outdated.

### ISSUE THREAD

**Issue by kasipavankumar** [greykoalacode/recogNoice#1]
Hello there, it seems like the packages in both frontend and backend are outdated. Please perform `npm update` for both of them. Recently, many of them got a security update which might be important.

Great work by the way, cheers!

**Comment by greykoalacode** [comment]
Hello there, thanks for the observation! I've updated the packages and have pushed them to main repo. Thank you

**Comment by kasipavankumar** [comment]
Cool.
